name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Wayland development libraries
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev pkg-config
    - name: Install ALSA development libraries
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config  
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
